services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: laravel-app
    volumes:
      - .:/var/www
    depends_on:
      - postgres
    user: root

  web:
    image: nginx:latest
    container_name: nginx-web
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    user: root

  postgres:
    image: postgres:15
    container_name: laravel-db
    environment:
      POSTGRES_DB: mercadoLibreApp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mercadoLibreApp
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  node:
    image: node:latest
    container_name: node-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    user: root

volumes:
  dbdata: